# Version of docker-compose
version: '3.7'

# Defines the containers 
services:
  # First project container 
  api:
    # Build parameters for the container
    build:
      # Declares that the container should be built from the current directory
      context: .
    ports:
      # Maps ports to be accessed by the app outside of the container
      - "4000:4000"
    depends_on:
      # The `db` container needs to be started before `web` is started
      - db
  # Second project container
  db:
    # Declares which Postres image to use
    image: postgres:latest
    # Declare a volume to not loose database data when stopping the container
    volumes:
      - postgres:/var/lib/postgresql/data
    # Maps port to be accessed by `web` container
    ports: 
      - "4321:4321"
# This needs to be declared because `volumes` was uesd in the `db` container
# Tells Docker to create a volume on the host machine to maintain data
volumes:
  postgres: